
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID,
		XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR,
		XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR,
		XPAR_MICROBLAZE_0_AXI_INTC_HAS_FAST,
		XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RESET_VALUE,
		XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_MICROBLAZE_0_AXI_INTC_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			}
		}

	}
};

